### ISSUE TITLE
A1465 11 ich

### ISSUE THREAD

**Issue by Shazz00** [MuertoGB/SMCFT#1]
Programed after power management issu and smc issu ![image](https://user-images.githubusercontent.com/123956125/232485891-cc04f1ec-43bc-43c2-98d7-afacadfd2598.jpeg)

**Comment by MuertoGB** [comment]
Why did you program the SMC? What is your logic board model, 820-xxxx?

**Comment by Shazz00** [comment]
Sir 980 YFC a1465 '' file 980YFE  SMC (A1466) will work ?.

**Comment by MuertoGB** [comment]
If it's the same year. Please answer the questions so I can solve and lock this.

**Comment by Shazz00** [comment]
820-3435-B

**Comment by Shazz00** [comment]
![image](https://user-images.githubusercontent.com/123956125/234794122-78d22af1-94ec-40dc-b869-066b742d429d.jpeg)

**Comment by MuertoGB** [comment]
Please run smbinfo.efi and return me your board-id:
https://github.com/MuertoGB/SMCFT/blob/main/BOARD-ID.md

You may cover up your serial numbers.

**Comment by Shazz00** [comment]
820-3435-B 2014 year A1465

**Comment by Shazz00** [comment]
![image](https://user-images.githubusercontent.com/123956125/234810845-fa2dda2f-e595-4b43-bd08-dfee792d0e2c.jpeg)

**Comment by MuertoGB** [comment]
I've checked the payloads, and they're correct. Flashing with 820-3435.nsh should cause no issue. Flash again with 3435.nsh.
