### ISSUE TITLE
820-3462 Compatibility

### ISSUE THREAD

**Issue by base64bits** [MuertoGB/SMCFT#2]
Hi, 

Thanks so much for creating this tool, I have a few 820-3462 boards that I have collected over the years, this and 820-00165 are the boards that I have had to swap the SMC, with your tool this is now super fast and if I dont have the correct SMC I can now use one from another board.

I could not find an option for the 820-3462 boards, do you know of one from the other options that may work so I can try? If not how can I collaborate so we can get this option as well?

Thanks again!

**Comment by MuertoGB** [comment]
LM4F 2012 is not currently supported, flashing a donor requires four payloads... EPM, Base, Update, App Code; currently we can only get the App Code for 2012 Stellaris. People have mentioned flashing with just the App Code, however, this is not acceptible in my opinion.

So for now, there is no option apart from a donor SMC from a matching board.

**Comment by protocold** [comment]
after almost 2 years, is there a way to do this now?

**Comment by MuertoGB** [comment]
> after almost 2 years, is there a way to do this now?

No, I haven't pursued further development of this project for some while. Unfortunately, there’s limited interest in supporting pre-2013 Macs, which makes it difficult to justify additional time investment. Additionally, I no longer encounter these older machines and don't have access to the necessary hardware for testing.

**Comment by protocold** [comment]
I do have both good and bad board, can you let me know how I can help them dump the firmware from the good board?
