### ISSUE TITLE
Flashed wrong SMC Version

### ISSUE THREAD

**Issue by stilltli** [MuertoGB/SMCFT#3]
Hi, thank you for this tool, i tried to fix and issue on an 820-3227 and found this tool. Under the impression, that 820-3227 and 820-5509 are the same, i flashed the later.

Luckily the Mac Mini seems not to be bricked, as it still boots into the OS, but the SMC of course is bogged as some this (e.g. fan control, front light etc.) do not work.

Can i somehow help to make this tool compatible with the 820-3227 board? I still have another 820-3227 here, but i do not know if it is possible to extract the files somehow.

Kind regards,
stilltli

**Comment by MuertoGB** [comment]
You have a 2012 LM4F, it's highly doubtful you can recover from this without replacing it with a matching donor.

Please get you me your board-id, and post it here.

**Comment by stilltli** [comment]
Sure, that would be:
Mac-031AEE4D24BFF0B1 for the MacMini 6.1 (the one i have)
Mac-F65AE981FFA204ED for the MacMini 6.2 (the Server Model of the former, i'm pretty sure those two model are identical except the cpu configuration)

Thank you very much!

**Comment by MuertoGB** [comment]
As suspected, there are no 4 part payloads for this device, so you will have to remove the SMC and replace it with a matching donor.

I will close here as there's nothing else to be done.

**Comment by stilltli** [comment]
Alright, thank you
